#!/usr/bin/with-contenv bash

cd /tdarr || exit 1
echo "[\$(date '+%Y-%m-%d %H:%M:%S')] Changed working directory to /tdarr"

echo "[\$(date '+%Y-%m-%d %H:%M:%S')] Starting Tdarr Node Updater..."
exec ./Tdarr_Updater

echo "[\$(date '+%Y-%m-%d %H:%M:%S')] Waiting for node to finish setup..."
sleep 60

exec ./Tdarr_Node
